services:
  postgres:
    container_name: postgres-sql-pauto
    image: postgres
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: social_media_book
    volumes:
      - postgres:/data/postgres
    ports:
      - 5432:5432
    networks:
      - spring-book
    restart: unless-stopped

  keycloak:
    container_name: keycloak-pauto
    image: quay.io/keycloak/keycloak:24.0.2
    ports:
      - 9090:8080
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    networks:
      - spring-book
    command:
      - "start-dev"
  mail-dev:
    container_name: mail-dev-pauto
    image: maildev/maildev
    ports:
      - 1080:1080
      - 1025:1025
networks:
  spring-book:
    driver: bridge

volumes:
  postgres:
    driver: local
  keycloak:
    driver: local